default: true
# Allow limit breakthroughs in the code block and table row lengths. The
# default is unconditional prohibition. It is exceptionally allowed in
# these elements due to folding difficulties.
line-length:
  code_blocks: false
  headings: false
  tables: false
# Allows the use of duplicate headings across different sections while
# still catching true duplicates among sibling headings.
no-duplicate-heading:
  siblings_only: true
# Allows embedding of the specified HTML tag. The default is unconditional
# prohibition. Allow for some valuable features, such as folding.
no-inline-html:
  allowed_elements:
    - details
    - summary
