services:
  app:
    command: ["sh", "./scripts/docker-dev-start.sh"]
    user: root
    volumes:
      - .:/app
      - app-node-modules:/app/node_modules
      - app-next-cache:/app/.next

volumes:
  app-node-modules:
  app-next-cache:
